### ISSUE TITLE
Ensure that `nav ul` styles are not bad for accessibility

### ISSUE THREAD

**Issue by aarongarciah** [mozdevs/cssremedy#15]
After reading this article by @scottaohara https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html I want to open a discussion about this particular rule (`list-style: none`) https://github.com/mozdevs/cssremedy/blob/8108c97ce590aed9e315fce4b72824f3b09faffc/remedy.css#L68

There are evidences that it is problematic using VoiceOver with Safari (macOS and iOS), it removes the list semantics.

As @scottaohara points in the article, using one of these rules maybe is better to avoid removing list semantics:

```css
list-style: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg'/%3E");

// or

list-style: url(#!);
```

It's a bit hacky, maybe it's worth it.

PS: thanks for this project 👌

**Comment by scottaohara** [comment]
Hey @aarongarciah, thanks for reading / the ping.

It's worth noting that I found some instances of visual quirks with IE11 and Edge per the method you mentioned, as I referenced in that section of the article.

The following snippet works much more consistently as a CSS method to re-introduce list semantics for unstyled lists:

```css
.list li {
  list-style-type: none; /* remove bullets */
}
 
.list li:before {
  content: "\200B"; /* add zero-width space */
  position: absolute; /* ensures it doesn't cause a gap */
}
```

It's also worth noting reasoning was given for Webkit's behavior here, and some of the proposed revisions (e.g. Webkit continuing to remove semantics of lists within navs, but not doing so outside of a nav), took place in [this twitter thread](https://twitter.com/cookiecrook/status/1084142936583892992).

As the very least, if no change were made to the CSS here, that a comment would be added to note that such a rule would remove semantics in Webkit based browsers, and options to re-add those semantics if the developer choose to do so.
