### ISSUE TITLE
Better defaults for <figure>?

### ISSUE THREAD

**Issue by tigt** [mozdevs/cssremedy#17]
I can’t find if a spec recommends this, but modern browsers add `margin: 1em 40px` to `<figure>`, such as this declaration from Firefox’s `html.css` UA stylesheet:

```css
blockquote, figure {
  display: block;
  margin-block-start: 1em;
  margin-block-end: 1em;
  margin-inline-start: 40px;
  margin-inline-end: 40px;
}
```

The `1em` is reasonable and matches `<p>`, but giving up 80 pixels out of 320 on most phones seems like a lot — 25%!

The unit mismatch also bothers me, but I’m not sure that’s an actual problem.

**Comment by frivoal** [comment]
Tempted to agree, but one thing to consider: `40px` is used on a number of things, in particular the inline-start padding of ul, ol, menu, dir, and margin of dd. Maybe there's some merit to keeping these things in sync.

**Comment by meyerweb** [comment]
Me, I’d love to see a global find-and-replace of `s/40px/2.5em/` (or `2.5rem`, if we absolutely _must_).  “Because that’s what Mosaic did” is exactly the kind of reasoning I believe cssremedy is trying to leave behind.

**Comment by frivoal** [comment]
I'd go with `em`s, not `rem`s. List markers and their spacing scale with the font size, so 40px fails at large sizes, and `rem`s would as well.

I don't know whether it's important to keep figures and list in sync. it might be. But @tigt 's point about limited space on mobile is valid too.

**Comment by jensimmons** [comment]
> “Because that’s what Mosaic did” is exactly the kind of reasoning CSS Remedy is trying to leave behind.

EXAAAACCTLY. I love that quote. I think I'll add it to the README.

**Comment by mirisuzanne** [comment]
I think this is a reasonable enhancement for modern browsers, using the same logical-properties that they apply in the user-agent styles, without much effort also "fixing" legacy browsers. 

The most direct replacement probably looks like:

```css
blockquote, figure {
  margin-inline-start: 2.5em;
  margin-inline-end: 2.5em;
}
ul, ol, menu, dir {
  padding-inline-start: 2.5em;
}
dd {
  margin-inline-start: 2.5em;
}
```

I'm going to start there, but I agree we could consider something smaller. Not sure what that value would be…
