### ISSUE TITLE
Table layout should be sane

### ISSUE THREAD

**Issue by eallenOP** [mozdevs/cssremedy#39]
From: https://wiki.csswg.org/ideas/mistakes

For example, who ever wanted non-collapsed borders (or no borders) by default? Not sure if borders count as layout though...

Padding? Tables without padding are not readable.

**Comment by jensimmons** [comment]
This sounds good. 
Do you have some suggestions for code to add to Remedy? 
(You can write it here so we can discuss, no need to be sure / make a pull request.)

**Comment by tylersticka** [comment]
I took a look through [our](https://cloudfour.com/) last several design system projects, and found a surprising amount of variation (to me, anyway) between table styles when it came to properties like `padding`, `border-spacing` and even `width` (I _really_ thought we'd be applying `width: 100%`, but I found two projects where we are not).

These styles were the only ones that we seemed to consistently apply as defaults (including comments that accompanied these in one of the source files):

```css
/**
 * 1. Prevent double borders
 * 2. Without this, th elements won't inherit their alignment predictably in
 *    Safari. Setting alignment here makes it easier to override on the
 *    containing element (if desired).
 */

table {
  border-collapse: collapse; /* 1 */
  text-align: left; /* 2 */
}

/**
 * Make th alignment consistent with td alignment
 */

th {
  text-align: inherit;
}
```

This doesn't address the "padding readability" issue, and our techniques, customers and end users may differ from others, but I thought I'd provide as a point of discussion and consideration. 🙂

**Comment by eallenOP** [comment]
How opinionated should this be? For example, is a table more table-ish when it has borders than when it doesn't? Is there any use at all in a table where every bit of content is squished right up against its neighbours? If we do want padding, how would we decide how much? 

In which case do we add something like:
```css
th, td {
  border: 1px solid black;
  padding: 5px;
}
```
or is this way too opinionated (and everyone will set their own table styles anyway)?

**Comment by hacknug** [comment]
The amount of padding should/could be consistent with the spacing scale used for headings and paragraphs.

**Comment by tylersticka** [comment]
> or is this way too opinionated (and everyone will set their own table styles anyway)?

I hope others will chime in (as I wouldn't want direction to be informed by my team's experience alone), but `border` and `padding` styles are among the first things that we seem to customize per project (and not consistently so). My instinct would be to leave them out.

**Comment by scottkellum** [comment]
I like it! I’d maybe amend it to be like this

```css
th, td {
  border: 1px solid;
  padding: 0.5rem;
}
```

`currentColor` is the default for border so there is no need to write it. Also padding in rem allows it to fit better with the chosen base font size so it can scale up and down based on foundational design decisions of that project.
