### ISSUE TITLE
UI system fonts by default?

### ISSUE THREAD

**Issue by eallenOP** [mozdevs/cssremedy#43]
I know this is low-hanging fruit, but I'm procrastiworking.
So, basically this necolas/normalize.css#665. Normalize stuck with `sans-serif`, but others (e.g. [Reboot](https://getbootstrap.com/docs/4.0/content/reboot/#native-font-stack), modern-normalize) go with system UI fonts.

There are plenty of examples of authoritative sites using a system UI stack (the words you're reading now: case-in-point). The idea is [not new](https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/), obviously. 

So stick with Times/TNR, go with `sans-serif`, or this?
```css
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif;
}
```
(Reboot still has `html { font-family: sans-serif; }` as well as the above)
Or something else?
