### ISSUE TITLE
Including upcoming properties that aren't in browsers yet?

### ISSUE THREAD

**Issue by frivoal** [mozdevs/cssremedy#8]
Are you also interested in properties that haven't been (broadly) implemented yet, but for which we know the initial value and legacy behavior will not be the best behavior, and lets people opt into better behavior? If yes, I suggest:
```css
:root { line-sizing: normal; }
```
and
```css
:root {
  text-spacing: trim-start allow-end trim-adjacent ideograph-alpha ideograph-numeric;
}
```
